A few relevant papers which have landed in (or near) the Hotspot VM.
evnm/research-in-production pull request #1
Opened 2017-01-10 19:57 UTC by bitbckt

2017-01-10 20:14 UTC, evnm requested changes
Dumb nits

2017-01-10 20:14 UTC, evnm commented on java.md
> +_Urs Hölzle, Craig Chambers and David Ungar_
Oxford comma, please

2017-01-10 20:14 UTC, evnm commented on java.md
> +_Urs Hölzle, and David Ungar_
Rm oxford comma

2017-01-10 20:14 UTC, evnm commented on java.md
> +_Cliff Click, and Michael Paleczny_
ditto

2017-01-10 20:14 UTC, evnm commented on java.md
> +_Christian Wimmer, and Michael Franz_
ditto

2017-01-10 20:14 UTC, evnm commented on java.md
> +_Tony Printezis, and David Detlefs_
ditto

2017-01-10 20:17 UTC, AlexDenisov commented
Aren't papers supposed to be in alphabetical order?

2017-01-10 20:47 UTC, evnm commented
Good point. The Java and .NET lists are in the same order in which they appeared on your and @mattwarren's blogs. Which of the following schemes do you think it'd make most sense to standardize on?

- Alphabetical by title
- Alphabetical by first author
- Chronological by date of publication

2017-01-10 21:09 UTC, AlexDenisov commented
I used alphabetical order by title.
Also, I realised that so far only my list has some particular order.
So it's totally up to you to decide, @evnm :)

2017-01-10 22:36 UTC, bitbckt commented
Sort order wasn't defined in the guidelines. I'm happy to comply with whichever regime you prefer.

2017-01-11 02:34 UTC, evnm commented
I think we should order publications alphabetically by first author, since this is what most IEEE-style papers themselves do. However, let's tackle that in a separate change.

2017-01-11 02:34 UTC, evnm approved these changes

2017-01-11 02:34 UTC, merged